# `NumPy`: Numerical operations in Python

This tutorial uses material also found in the [SciPy 1.0 Nature Methods](https://www.nature.com/articles/s41592-019-0686-2) and [NumPy Array IEEE](10.1109/MCSE.2011.37) article and at [https://numpy.org/](https://numpy.org/).

### Learning outcomes:
 - Understand Python Library `NumPy`
 - Use `numpy arrays`
 - Apply loops and logical operators on `numpy arrays`

Data scientists spend a lot of time – wait for it – working with ***data***! To work with **data** it is critical to organize the data in a way that facilitate the work on the potential analyses we might need to do. So organizing data means guessing what type of work we will want to do with the dataset. And, odd is it may seem, good guessing requires some practice. The data organization process will require: 

* store the data a clear and systematic way
* provide methods to access the data that are simple and straightforward
* be flexible enough so to and allow to modify the format of the data for various needs

NumPy is the fundamental `library` for mathematical operations and computations in Python. 

The NumPy array is a multidimensional array object. A variety of fast operations on arrays are provided by NumPy. These include operations that are mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more. 

NumPy is the base of scientific computing and data science libraries such as [Pandas](https://pandas.pydata.org/) [scipy.org](https://scipy.org/), and [scikit-learn.org](https://scikit-learn.org/) among many others.

In other (simpler?) words, Numpy arrays are grids or tables for holding, accessing, and manipulating data. They are created and accessed in ways that are very similar to the ways Python `lists` can be accessed.

So what we are going to do is to recall how `lists` work (lists are handy!), then we will graduate to `numpy arrays` and see what they can do. 

### Python lists

We have covered Python `lists` (and other datatypes) in previous tutorials. Python `lists` (a list of things) is build by collecting, ahem, a list of things using `[square brackets]`.

For example:

In [1]:
mylist = ['this', 3, 'list', 4+2j, 6.66]

We can address elements in a list by using indices and the `:` (colon) operator.

In [2]:
mylist[0:3]

['this', 3, 'list']

We can read this as "Give me all the elements in the interval between 0 **inclusive** to 3 **exclusive**."

I know this is weird. But at least for any two indexes `a` and `b`, the number of elements you get back from `mylist[a,b]` is always equal to `b` minus `a`, so I guess that's good!

We can get any consecutive hunk of elements using `:`.

In [3]:
mylist[2:5]

['list', (4+2j), 6.66]

If you omit the indexes, Python will assume you want everything.

In [4]:
mylist[:]

['this', 3, 'list', (4+2j), 6.66]

List can obviously host also homogeneous types of data, such as `int` or `float`:

In [5]:
mylistHomogeneous = [2, 3.14, 10.5, 11.13, 12.7, 4.31]

### Numpy Arrays

Numpy arrays were designed to be lists with superpowers, so everything we learned about  `lists` will apply to `numpy arrays` as well!

A NumPy array is a multidimensional, uniform collection of elements (that is, all elements occupy the same number of bytes in memory). An array is characterized by
 - the type of elements it contains and
 - its shape. 
 
For example, a matrix might be represented as an array of shape M×N that contains numbers, such as floating-point or complex numbers. Unlike matrices, NumPy arrays can have up to 32 dimensions; they might also contain other kinds of elements (or even combinations of elements), such as Booleans or dates. [Ref. Van Der Walt et al. IEEE](10.1109/MCSE.2011.37)

Not to state the obvious, but to use `numpy arrays`, we'll need to `import` the library `numpy`. The standard is to import `numpy` as `np`:

In [6]:
import numpy as np

`arrays` can be made by simply asking for one and filling it out with values, in much the same way we make a `list`.

In [7]:
myarr = np.array([2, 4, 6, 8, 9, 10])

The command `print` can be used also on `NumPy arrays` and it returns the content of the array:

In [8]:
print(myarr)

[ 2  4  6  8  9 10]


By simply returning the array object name (`myarr`) the output is a bit more informative and it returns the type (`array`):

In [9]:
myarr

array([ 2,  4,  6,  8,  9, 10])

From then on, all the indexing we've learned so far applies directly! Square brackets are used for indexing and the same type of addressing can be used as we have learned for `lists`:

In [10]:
myarr[4]

9

In [11]:
myarr[-3:]

array([ 8,  9, 10])

$\color{blue}{\text{Complete the following exercise.}}$

  - Create a `NumPy array` containing both `int`, `float` and `complex` datatypes.

  [Use the cell below to show your code]

In [12]:
arr = np.array([1, 2.4, 1.5+3.4j])
print(arr)

[1. +0.j  2.4+0.j  1.5+3.4j]


  - Create a `NumPy array` containing `str` as datatypes.

  [Use the cell below to show your code]

In [13]:
arrStr = np.array(['hello', 'world', 'bye'])
print(arrStr)

['hello' 'world' 'bye']


### Operations on `numpy arrays`: the difference between `lists` and `arrays`
Indeed, we can make an array directly out of a list.

In [14]:
myArrFromList = np.array(mylistHomogeneous)

In [15]:
myArrFromList

array([ 2.  ,  3.14, 10.5 , 11.13, 12.7 ,  4.31])

And then of course we can index it exactly the same way, so... *Wait, why are we making arrays now? What's the difference?*

One **huge** difference is that if we wanted to do some math with basic Python lists, the fact that they can hold multiple types of data elements does not assure that the mathematical operations will perform.

In [61]:
mylistHomogeneous + 5

TypeError: can only concatenate list (not "int") to list

`numpy` arrays instead contain numerical elements by definition. This definition assures the ability to perform math ith the arrays. So, whereas the addition above did not work when using the `list`, it does work when using the `numpy` array, even though both `list` and `array` contain the same elements!

In [17]:
myArrFromList + 5

array([ 7.  ,  8.14, 15.5 , 16.13, 17.7 ,  9.31])

Now **that** seems like it might be useful!

$\color{blue}{\text{Complete the following exercise.}}$

  - What happens when you add a number to a `NumPy array`? How do the content of the array change?
  
  If you add a number to a `Numpy array`, the number is added to every element in the `Numpy array`. Thus, the entire content of the array changes (i.e. every element is increased by the number that's being added).

In [18]:
arr = np.array([2, 5.5, 7])
print("original: ", arr)
print("add two: ", (arr + 2)) # add 2 to numpy array

original:  [2.  5.5 7. ]
add two:  [4.  7.5 9. ]


  - Create a new `array` and multiply the array by a complex number:

  [Use the cell below to show your code]

In [19]:
arrMult = np.array([2, 5.5, 7])
print("original: ", arrMult)
print("multiply by 2+3.2j: ", (arrMult * 2+3.2j)) # multiply array by a complex #

original:  [2.  5.5 7. ]
multiply by 2+3.2j:  [ 4.+3.2j 11.+3.2j 14.+3.2j]


The complex number is multiplied to every element in the `Numpy array` such that the entire content of the array changes. Thus, every element is increased by a factor of the complex number.

### More operations on `arrays`

Two arrays can be added, or subtracted, or multiplied or whatever!

In [20]:
myarr + myArrFromList

array([ 4.  ,  7.14, 16.5 , 19.13, 21.7 , 14.31])

In [21]:
myarr * myArrFromList

array([  4.  ,  12.56,  63.  ,  89.04, 114.3 ,  43.1 ])

In [22]:
myarr / myArrFromList

array([1.        , 1.27388535, 0.57142857, 0.71877808, 0.70866142,
       2.32018561])

We can also **combine** our 2 arrays into a single ***two dimensional (2D) array***.

In [23]:
twoDarr = np.array([myarr, myArrFromList])

In [24]:
twoDarr

array([[ 2.  ,  4.  ,  6.  ,  8.  ,  9.  , 10.  ],
       [ 2.  ,  3.14, 10.5 , 11.13, 12.7 ,  4.31]])

Simple though this may seem, *2D arrays just like this are the bedrock of data analysis!* Arrays of real data are usually larger – sometimes much much larger! – but all the principles are the same and all you as a Data Scientists need to remember is the dimensionality of the data arrays. Python will then compute what you ask for.

But, hold on one second. Remembering the dimensionality of the array is ** *very* ** imoortant. Indeed Python can perform some operations if two arrays do *not* have the same dimensions, but other operations are likely to fail.

For example, imagine two `arrays` with different dimensions:

In [25]:
smallArray = [2, 3, 4]
largeArray = [2, 3, 4, 5, 6, 7]

The two arrays can be added together by using the symbol `+`:

In [26]:
smallArray + largeArray

[2, 3, 4, 2, 3, 4, 5, 6, 7]

Yet, the same two arrays cannot be multiplied:

In [62]:
smallArray * largeArray

TypeError: can't multiply sequence by non-int of type 'list'

This is because Python cannot identify elements to match during the multiplication.

$\color{blue}{\text{Complete the following exercise.}}$

  - What happens when you add two arrays of different dimensions? Say one array with 6 complex numers and one with 4 `float` numbers?

      [Use the cell below to show how to create and add the two arrays]

In [57]:
arr6 = np.array([2+3j, 3+4.5j, 2.1+4j, 7.5+2j, 4.5+7j, 8.2+9j ])
arr4 = np.array([5.4, 6.7, 3.5, 9.4])
print(arr6 + arr4) # add arrays of different dimensions

ValueError: operands could not be broadcast together with shapes (6,) (4,) 

Adding the two arrays result in an error because the dimensions do not match (error message says: "operands could not broadcast together with shapes (6,) (4,)). Thus, you can't add two arrays of different dimensions.

### Methods of `numpy arrays`

So the shape of the array (the dimensionality) is key, especially if we plan on doing math with the arrays, whihc is the primary goal of the arrays! 

`numpy arrays` are Python objects and as such they have `methods`. A variety of methods exist for the array and `shape` is the one that allow us to retrieve the dimensionality of an array.

In [29]:
twoDarr.shape

(2, 6)

Unlike lists, which are always just lists, arrays can come in any shape. So it's *really* convenient that they can tell us what shape they are straight away.

Indexing into 2D arrays is a straightforward extension of indexing into 1D arrays or lists. We just provide a second index after a `,` (comma). Like this.

In [30]:
twoDarr[1,3]

11.13

The first index refers to the **row index**, and the second to the **column index**. In this case, we're asking for the value in the second row and the fourth column, which is indeed 7 (remember *the first row and column are index=0!*).

We can play all the same games indexing with 2D arrays as we can with 1D arrays, we just have to remember that everything before the comma `,` refers to the *rows* in that it specifies locations along the *vertical dimension*, and everything after the comma `,` refers to the *columns* in that it specifies locations along the *horizontal dimension*.

So this:

In [31]:
twoDarr[:,0:3]

array([[ 2.  ,  4.  ,  6.  ],
       [ 2.  ,  3.14, 10.5 ]])

means "Give me all the rows (the colon `:`) in the first 3 columns (the "`0:3`)."

I told you that the colon all alone by itself would end up being useful!!! In this case for example, by using the `:` you do not need to type many indices (one per row) and you even do not need to remmeber how many rows there are, just use `:` and Python will return all the elements.

A few more examples:

In [32]:
# the last row (regardless of the number of rows, 
# again you do not need to knowhow many rows exist)
twoDarr[-1,:] 

array([ 2.  ,  3.14, 10.5 , 11.13, 12.7 ,  4.31])

In [33]:
twoDarr[:,-2:] # last two columns

array([[ 9.  , 10.  ],
       [12.7 ,  4.31]])

In [34]:
twoDarr[0,::2] # first row, every other column

array([2., 6., 9.])

To get good at this, you don't need natural born talent or anything like that. Like so much in life, the key is *practice, practice, practice*!!! So play around! You can't break your computer or anything!

Another neat trick that arrays can do is *transpose* themselves, flipping the rows for columns.

(Hold your right hand in front of your face so that you're looking at your palm with your fingers pointing towards the left. Now flip your hand so that you're looking at the back of your hand with your fingers pointing up. You just *transposed* your hand such that the first row (your pointer finger) became the first column!)

In [35]:
colarr = twoDarr.T

In [36]:
colarr

array([[ 2.  ,  2.  ],
       [ 4.  ,  3.14],
       [ 6.  , 10.5 ],
       [ 8.  , 11.13],
       [ 9.  , 12.7 ],
       [10.  ,  4.31]])

Why would we want to do that? By convention, *variables* in datasets should correspond to the columns, and *observations* should correspond to the rows. So we have taken data in which this was not so and turned it into an array in which the columns are the first few non-prime numbers and the prime numbers, respectively, and the rows correspond to the instances in order (1st , 2nd, 3rd, ....).

We have just done a little of what is known as **data wrangling**. While not as fun as data visualization, data wrangling is often a big part of any analysis project!

Now that we have the data into shape, we can unleash all the powers of numpy arrays, powers which pandas DataFrames will inherit and build upon!

For example, who's bigger overall, the primes or the non-primes?

In [37]:
colarr.sum(0)

array([39.  , 43.78])

The primes win! 
In `colarr.sum(0)`, the 0 means "the first (vertical) dimension", i.e., sum the values *across the rows* within each column. To sum along the second dimension, we do:

In [38]:
colarr.sum(1)

array([ 4.  ,  7.14, 16.5 , 19.13, 21.7 , 14.31])

So any numpy array knows how to add up the numbers in it by row or by column (see what happens if you leave off the dimension, like this `colarr.sum()`. The list of things that numpy arrays can do themselves is pretty impressive.

Check it out [here](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html).

(or paste this into your browser: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)

$\color{blue}{\text{Complete the following exercise.}}$

  - How many methods does a numpy array have? 70
  
  - Create a new 2-dimensional array, and show the use of two methods not used above (`prod` and `round` could be two simple ones, but no pressure):
  
  [Use the cell below to show how to create and add the two arrays]
  
*Hint:* The symbol `?` can be used at the end of a method and that can help understand how to use the method, for example, `myarray.shape?`

In [39]:
twoD_arr = np.array([[1,2,3], [4,5,6]])
# use two methods not used above
print("max: ", np.amax(twoD_arr))
print("min: ", np.amin(twoD_arr))

max:  6
min:  1


### `NumPy` methods to create arrays

Often, we want to create a array that we know we're going to put values in later. For example, we might be planning on doing a computation that will result in 3 sets of 7 values, and we want be able to store them directly into an array. We can pre-make an array filled with zeros with `np.zeros(r, c)`.

In [40]:
myzeros = np.zeros((7, 3))

In [41]:
myzeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Another handy method to create arrays is `ones`

In [42]:
myones = np.ones((3,4))

In [43]:
myones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

We will encounter other `NumPy` methods in later tutorials. For the time being one last method that will turn out very handy when modelling data:

In [44]:
myRandomNumArray = np.random.randn(10,1)
print(myRandomNumArray)

[[-0.23449062]
 [ 0.13996888]
 [ 0.17277323]
 [-1.87516832]
 [ 1.38406704]
 [-1.77103498]
 [ 0.4935666 ]
 [-0.22058697]
 [ 0.43432616]
 [-1.58782289]]


The `numpy` submodule `random` contains a variety of methods to create arrays containing random numbers. Generating random numbers is helpful in many applications, for example, they can be used to create normally distributed noise, or data with normally distributed noise, etc. 

$\color{blue}{\text{Complete the following exercise.}}$
  
  - Create a new 1-dimensional array of uniformly-distributed random number:
  
  [Use the cell below to show your code]


In [45]:
uniform_rand = np.random.random(5)
print(uniform_rand)

[0.71594983 0.67351369 0.62352633 0.23633233 0.34907952]


  
  - Create a new  2-dimensional array of normally-distributed random number:
  
  [Use the cell below to show your code]


In [46]:
normal_rand = np.array([np.random.normal(5, 3, 10), np.random.normal(5, 3, 10)])
print(normal_rand)

[[ 8.71507651  2.40166293  1.33120233  4.1438233   6.35988851  6.25827422
   8.65597146  6.32473758  3.10469456  2.80690695]
 [17.69128796  6.38314625 -0.09823965  7.73760032  2.53293884  1.03724024
   1.03555711  4.59310268  6.59291377  2.02660561]]


Let's now create a simple 1-D array and explore what happens when we add a number to the values and what happens when we multiply the numbers in the array:

In [47]:
size  = 20
origArray = np.random.randn(size,1)

Let's look at the values in the array.

In [48]:
print(origArray)

[[ 0.10213072]
 [ 0.57279524]
 [ 0.08088231]
 [-1.12561701]
 [ 0.26292391]
 [ 1.01129083]
 [-0.00653315]
 [-1.24120304]
 [-2.06874953]
 [-0.13983597]
 [ 0.58501304]
 [-1.46178071]
 [-0.47302698]
 [-0.07353737]
 [ 0.56394763]
 [ 0.92878282]
 [ 0.27601317]
 [-1.41052208]
 [-0.26746551]
 [ 0.25098112]]


There seem to be a variety of numbers, some positive, some negative, as expected because `randn` is supposed to generate numbers centered at 0 (i.e., with mean 0) and standard deviation of 1.

Let's compute the standard deviation and mean of these numbers. Numpy provides to handy methods:

In [49]:
mean = np.mean(origArray)
sd = np.std(origArray)
print(['The mean is:', mean])
print(['the STD is:', sd])

['The mean is:', -0.18167552804499082]
['the STD is:', 0.8358489749148149]


Well, okay, the mean is not quite close to 0, but perhaps close enough? The standard deviation seems pretty close to the expected value of 1.

$\color{blue}{\text{Complete the following exercise.}}$
  
  - Create a new 1-dimensional array of 100 normally-distributed random numbers:
  
  [Use the cell below to show your code]


In [50]:
rand_100 = np.random.normal(10, 5, 100)
print(rand_100)

[14.61453637 12.47204356  1.90459538 13.12482812 11.35653212 13.05086793
  5.17132821 10.53008794 15.86321411  6.02002119  9.91024811  9.7081235
  2.2574159  19.93178336  9.23954568 14.96826377 19.60167092  6.39411828
  6.49646491  6.98017815 14.34907343 14.17886098 22.3358706  12.01840875
  8.37970494  8.82563939  3.60704481  4.39655604  7.20837312 21.70071488
 13.49205091  5.15354608  6.39530693  1.58680086 18.94625132 -2.50218832
  1.86761795  9.78057052  7.39353866  9.04414028 12.21914918  8.9707732
  5.76990817 13.39084306  9.34855145 13.2555578   1.85812582  7.4308973
  7.94236897 16.43495206 13.37612346 14.20094594 13.61760135  8.57757189
  5.29009676  8.70756297 11.9435701   1.71130272 21.24834017 -1.04361746
  4.14383833  6.81199974 13.55753724  2.14741358 11.37887325 13.95685177
 12.09303728 14.04985871 13.41695519 21.97568871  0.59388171  5.7624534
 17.88821101 12.2790752   6.60478018 13.64701542 11.80980483 11.6788794
 12.88514925 15.6184373  -0.3636151   4.06540242 14.3081

   - What happens to the mean and standard deviation after increasing the size of the array? Are they closer of further from the expected values? Why? 

In [51]:
# mean and standard dev when size = 100
mean_100 = np.mean(rand_100)
sd_100 = np.std(rand_100)
print(['The mean (n=100) is:', mean_100])
print(['the STD (n=100) is:', sd_100])

# mean and standard dev when size = 10000
rand_10000 = np.random.normal(10, 5, 10000)
mean_10000 = np.mean(rand_10000)
sd_10000 = np.std(rand_10000)
print(['The mean (n=10000) is:', mean_10000])
print(['the STD (n=10000) is:', sd_10000])

['The mean (n=100) is:', 10.38021051658703]
['the STD (n=100) is:', 5.542374166715658]
['The mean (n=10000) is:', 9.992081012827356]
['the STD (n=10000) is:', 4.996616502549034]


Both the mean and standard deviation is closer to the expected values when you increase the size of the array. This is because the law of large numbers describes this phenomenon: the greater the sample size, the more likely the mean and standard deviations are to be representative of the true/expected values. This is because individual variances in data points "even out" or are "more balanced" as you use a greater sample size when averaging.

What happens if we add 5 to the array?

In [52]:
x  = 5 + origArray

In [53]:
print(x)

[[5.10213072]
 [5.57279524]
 [5.08088231]
 [3.87438299]
 [5.26292391]
 [6.01129083]
 [4.99346685]
 [3.75879696]
 [2.93125047]
 [4.86016403]
 [5.58501304]
 [3.53821929]
 [4.52697302]
 [4.92646263]
 [5.56394763]
 [5.92878282]
 [5.27601317]
 [3.58947792]
 [4.73253449]
 [5.25098112]]


It looks like the values shifted. But how much? It looks like they recentered at 5, the value we added. So we can perhaps assume that now the distribution of numbers is normally distributed but with a mean of 5. The standard deviation has not bee changed. It is still at 1, trust me for the moment and let try multiplying the numbers.

In [54]:
x  = 2 * origArray
print(x)

[[ 0.20426143]
 [ 1.14559048]
 [ 0.16176462]
 [-2.25123402]
 [ 0.52584782]
 [ 2.02258166]
 [-0.0130663 ]
 [-2.48240608]
 [-4.13749906]
 [-0.27967193]
 [ 1.17002609]
 [-2.92356143]
 [-0.94605397]
 [-0.14707474]
 [ 1.12789526]
 [ 1.85756563]
 [ 0.55202633]
 [-2.82104416]
 [-0.53493101]
 [ 0.50196225]]


It looks like the values increased. There seem to be a larger variality, more bigger numbers, both negative and positive. So perhaps the STD is not at 1 anymore. Could it be at 2?

$\color{blue}{\text{Complete the following exercise.}}$
  
  - Compute the mean, std and median of `x`:
  
  [Use the cell below to show your code]

In [55]:
# compute and print the mean, std, and median of the origArray
orig_mean = np.mean(origArray)
orig_std = np.std(origArray)
orig_median = np.median(origArray)
print("origArray")
print("mean: ", orig_mean , ", std: ", orig_std, ", median: ", orig_median, "\n")

# compute and print the mean, std, and median of the modified x array
mean = np.mean(x)
std = np.std(x)
median = np.median(x)
print("x = 2 * origArray")
print("mean: ", mean , ", std: ", std, ", median: ", median)

origArray
mean:  -0.18167552804499082 , std:  0.8358489749148149 , median:  0.037174579652150826 

x = 2 * origArray
mean:  -0.36335105608998164 , std:  1.6716979498296298 , median:  0.07434915930430165


  
  - What are the mean, std and median of `x`? Why, what is going on here?
  
 From the above cell, we can see that the values of the mean, standard deviation and median of the `x` array was multiplied by two compared to the `origArray`. This occurs because if you mutliply a distribution by 2, it affects the mean, standard deviation and median such that all of these values are multiplied by the same number you multiplied the entire distribution (e.g. 2).

### Summary

So in this tutorial we have shown how to organize and manipulate data using Python `numpy` `arrays`.

So those are the basics of numpy arrays. They:

* store values in rows and columns
* each dimension starts at index zero (like lists)
* can be accessed using
    - square brackets `[]` with row and column indexes separated by a comma
    - integer indexes (including negative "start from the end" indexes)
    - a colon `:` (or two if you want a step value other than 1)
* can have maths done to every element in one go
* can be added, subtracted, etc. from one another
* have superpowers! they can compute stuff along their rows and columns!

The operations that are available for these two data types will be the base for many things that you might need to do as a Data Scientist. 

`Numpy arrays` Can host a variety of data types. Although this might be too much for now, below a table of all the data types an `array` can support:

| Type	| Description |
| --- | --- |
| bool |	Boolean (True or False) stored as a bit (0, 1) |
| inti	| Platform integer (normally either int32 or int64) |
| int8	| Byte (-128 to 127) |
| int16	| Integer (-32768 to 32767) |
| int32	| Integer (-2 ** 31 to 2 ** 31 -1) |
| int64	| Integer (-2 ** 63 to 2 ** 63 -1) |
| uint8	| Unsigned integer (0 to 255) |
| uint16	| Unsigned integer (0 to 65535) |
| uint32	| Unsigned integer (0 to 2 ** 32 – 1) |
| uint64	| Unsigned integer (0 to 2 ** 64 – 1) |
| float16	| Half precision float: sign bit, 5 bits exponent, and 10 bits mantissa |
| float32	| Single precision float: sign bit, 8 bits exponent, and 23 bits mantissa |
| float64 or float	| Double precision float: sign bit, 11 bits exponent, and 52 bits mantissa |
| complex64	| Complex number, represented by two 32-bit floats (real and imaginary components) |
| complex128 or complex	| Complex number, represented by two 64-bit floats (real and imaginary components) |

$\color{blue}{\text{Complete the following exercise.}}$
  
  - Generate an 1-D array of mean = 10 and std = 1.5:
  
  [Use the cell below to show your code]

In [60]:
# generate 1D array with mean = 10 and std = 1.5
arr1D = np.random.normal(10, 1.5, 50)
print(arr1D)

# confirm that mean and std are similar to the expected values
mean = np.mean(arr1D)
std = np.std(arr1D)
print("mean: ", mean , ", std: ", std)

[ 8.444934   10.91429003 13.15099107  9.18253696  9.98630211  9.76643916
  8.74266553 11.26429457 10.9244247  10.7476944   9.50828907 10.45163275
  7.70989777 12.16074232  9.02247577 11.72895787 10.58330896 10.78822
 10.05423367  9.93348921  9.24664896  8.83138205  9.51070764 12.63110714
 13.13399357 13.04200103  8.72648549  9.07116839 12.00905242  9.26935718
 11.60808039  9.85646193  8.56258103  8.87223479  9.52588993  9.32385275
 10.2702386  12.41729565  7.27017182 11.82701906  8.89280738 11.1466884
  8.17097782  9.89130631  9.78365397 10.46797078 10.51103567 10.36882307
 11.55233486 10.06848602]
mean:  10.218512680610488 , std:  1.4065431669743451
